In [24]:
# Library
import numpy as np
import matplotlib.pyplot as plt
import pprint

In [16]:
#(1) Generate arrays for A matrix and b vector using NumPy library
A = np.array([[1, 1, -2],[3, 3, -5],[3, 3, -10], [1,1,-7], [-4,-4,11]])
b = np.array([2, 7, 2, -3, -4])
print(A, b)


[[  1   1  -2]
 [  3   3  -5]
 [  3   3 -10]
 [  1   1  -7]
 [ -4  -4  11]] [ 2  7  2 -3 -4]


In [33]:
#(2) Transpose A and apply matrix multiplication with the original matrix(A'A)
transA = A.T
print('Transpose A is')
print(transA)
ans = np.dot(transA,A)
print(ans)

Transpose A is
[[  1   3   3   1  -4]
 [  1   3   3   1  -4]
 [ -2  -5 -10  -7  11]]
[[ 36  36 -98]
 [ 36  36 -98]
 [-98 -98 299]]


In [34]:
#(3) Calculate x as the solution of A'Ax = A'b
# x = inv(A'A)*A'*b
ansinv = np.invert(ans)
print(ansinv)
B = np.dot(transA,b)
x = np.dot(ansinv,B)
print(x)

[[ -37  -37   97]
 [ -37  -37   97]
 [  97   97 -300]]
[-11062 -11062  32748]


In [ ]:
#(4) Calculate the norm of Ax - b with line-by-line coding and using Numpy library


In [42]:
#2. Drawing Graphs
x = np.arange(-4,4,1/100)
y = np.arange(-4,4,1/100)
f = -20 * np.exp(-0.2 * np.sqrt(0.5 *(x**2 + y**2))
    - np.exp(0.5 *(np.cos(2*np.pi) + np.cos(2*np.pi))) + 20 + np.exp(1))
X, Y = np.meshgrid(x, y)
print(f)

[-4.35997549e+09 -4.36870417e+09 -4.37745032e+09 -4.38621398e+09
 -4.39499519e+09 -4.40379398e+09 -4.41261038e+09 -4.42144443e+09
 -4.43029617e+09 -4.43916563e+09 -4.44805284e+09 -4.45695785e+09
 -4.46588068e+09 -4.47482138e+09 -4.48377998e+09 -4.49275652e+09
 -4.50175102e+09 -4.51076353e+09 -4.51979409e+09 -4.52884272e+09
 -4.53790947e+09 -4.54699437e+09 -4.55609746e+09 -4.56521877e+09
 -4.57435835e+09 -4.58351622e+09 -4.59269242e+09 -4.60188700e+09
 -4.61109998e+09 -4.62033141e+09 -4.62958132e+09 -4.63884975e+09
 -4.64813673e+09 -4.65744231e+09 -4.66676651e+09 -4.67610939e+09
 -4.68547096e+09 -4.69485128e+09 -4.70425038e+09 -4.71366830e+09
 -4.72310507e+09 -4.73256073e+09 -4.74203532e+09 -4.75152888e+09
 -4.76104145e+09 -4.77057306e+09 -4.78012376e+09 -4.78969357e+09
 -4.79928254e+09 -4.80889071e+09 -4.81851812e+09 -4.82816480e+09
 -4.83783079e+09 -4.84751613e+09 -4.85722087e+09 -4.86694503e+09
 -4.87668866e+09 -4.88645180e+09 -4.89623448e+09 -4.90603675e+09
 -4.91585864e+09 -4.92570