In [2]:
import numpy as np
import matplotlib.pyplot as plt

#### numpy : array 자료형[]을 이용한 수치계산 

패키지와 모듈을 불러오는 방법 

from 'library name' import 'package name or module name'

from 'library name' import * : 라이브러리 내의 모든 패키지 불러옴 --> 코드가 너무 길어지고, 충돌이 발생 할 수 있음

메모리 할당까지 모두 고민해서 transpose하도록 해놨으니 a.T를 사용하여라


In [4]:
a = np.random.random((2,3))
print(a)
# all
print(a.sum())
# column sum
print(a.sum(axis=0))
# row sum
print(a.sum(axis=1))


[[0.76699884 0.87358144 0.29318313]
 [0.27162073 0.19994471 0.55927555]]
2.9646044062566466
[1.03861957 1.07352615 0.85245868]
[1.93376341 1.03084099]
